### PR TITLE
Shorten Symfony Recipe URL Cache Keys

### LINKED ISSUE #830: File name too long
Just updated to Symfony Flex 1.17.2 and trying to run `composer recipes` I keep getting:

```bash
$ composer recipes
                                                                                                                                                                                                                                                           
  [ErrorException]                                                                                                                                                                                                                                         
  file_put_contents(/home/cameron/.cache/composer/repo/flex/https---api.github.com-repos-symfony-recipes-contrib-contents-friendsofsymfony.elastica-bundle.5.0.json-ref-flex-main.619ac205ee82c4.90304062.tmp): failed to open stream: File name too long 
```

Xubuntu 21.04, ext4, composer 2.1.12

The cache-key is generated from the URL, which needs to be shortened.

```bash
$ composer recipes -vv

                                                                                                                                                                                                                                                           
  [ErrorException]                                                                                                                                                                                                                                         
  file_put_contents(/home/cameron/.cache/composer/repo/flex/https---api.github.com-repos-symfony-recipes-contrib-contents-friendsofsymfony.elastica-bundle.5.0.json-ref-flex-main.619ac3b00e5ba8.11438895.tmp): failed to open stream: File name too long  
                                                                                                                                                                                                                                                           

Exception trace:
 () at phar:///home/cameron/bin/composer/src/Composer/Cache.php:152
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 file_put_contents() at phar:///home/cameron/bin/composer/src/Composer/Cache.php:152
 Composer\Cache->write() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Downloader.php:364
 Symfony\Flex\Downloader->parseJson() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Downloader.php:304
 Symfony\Flex\Downloader->Symfony\Flex\{closure}() at n/a:n/a
 call_user_func() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php:20
 React\Promise\FulfilledPromise->then() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:74
 React\Promise\Deferred->React\Promise\{closure}() at n/a:n/a
 call_user_func() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:166
 React\Promise\Deferred->processQueue() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:95
 React\Promise\Deferred->resolve() at n/a:n/a
 call_user_func() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php:20
 React\Promise\FulfilledPromise->then() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:76
 React\Promise\Deferred->React\Promise\{closure}() at n/a:n/a
 call_user_func() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:166
 React\Promise\Deferred->processQueue() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php:95
 React\Promise\Deferred->resolve() at phar:///home/cameron/bin/composer/vendor/react/promise/src/React/Promise/Promise.php:42
 React\Promise\Promise->React\Promise\{closure}() at n/a:n/a
 call_user_func() at phar:///home/cameron/bin/composer/src/Composer/Util/Http/CurlDownloader.php:415
 Composer\Util\Http\CurlDownloader->tick() at phar:///home/cameron/bin/composer/src/Composer/Util/HttpDownloader.php:403
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///home/cameron/bin/composer/src/Composer/Util/Loop.php:96
 Composer\Util\Loop->wait() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Downloader.php:310
 Symfony\Flex\Downloader->get() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Downloader.php:229
 Symfony\Flex\Downloader->getRecipes() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Flex.php:703
 Symfony\Flex\Flex->fetchRecipes() at /home/cameron/Projects/weirdly/vendor/symfony/flex/src/Command/RecipesCommand.php:84
 Symfony\Flex\Command\RecipesCommand->execute() at phar:///home/cameron/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///home/cameron/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/cameron/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///home/cameron/bin/composer/src/Composer/Console/Application.php:327
 Composer\Console\Application->doRun() at phar:///home/cameron/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///home/cameron/bin/composer/src/Composer/Console/Application.php:128
 Composer\Console\Application->run() at phar:///home/cameron/bin/composer/bin/composer:73
 require() at /home/cameron/bin/composer:29
```

### PR DESCRIPTION
**Pull request by cjunge**
Fixes #830.

This change replaces the simple generated composer filesystem cache key with a slightly shorter one only for the Symfony Recipes repos.

`/home/cameron/.cache/composer/repo/flex/https---api.github.com-repos-symfony-recipes-contrib-contents-friendsofsymfony.elastica-bundle.5.0.json-ref-flex-main` 
becomes
`/home/cameron/.cache/composer/repo/flex/sf-recipes-contrib-friendsofsymfony.elastica-bundle.5.0.json-ref-flex-main`

This won't fix other recipe files hosted on long paths.

### CODE REVIEW

**Comment by cjunge** [comment]
The failing tests appear to be due to an API change in Composer, unrelated to my code changes. Should I fix these?

```php
        $realPkg = new Package('real', '1.0.0', '1.0.0');
        $realPkgLink = new Link('lorem', 'real', class_exists(MatchAllConstraint::class) ? new MatchAllConstraint() : null, 'wraps', '1.0.0');

        $virtualPkgFoo = new Package('pack_foo', '1.0.0', '1.0.0');
        $virtualPkgFoo->setType('symfony-pack');
        $virtualPkgFoo->setRequires([$realPkgLink]);
```

```php
        $realPkg = new Package('real', '1.0.0', '1.0.0');
        $realPkgLink = new Link('lorem', 'real', class_exists(MatchAllConstraint::class) ? new MatchAllConstraint() : null, 'wraps', '1.0.0');

        $virtualPkgFoo = new Package('pack_foo', '1.0.0', '1.0.0');
        $virtualPkgFoo->setType('symfony-pack');
        $virtualPkgFoo->setRequires(['real' => $realPkgLink]);
```

File: src/Downloader.php [hunk 1]
```diff
@@ -412,4 +412,11 @@ private function initialize()
             $this->endpoints[$endpoint] = $config;
         }
     }
+
+    private static function generateCacheKey(string $url): string
+    {
+        $url = preg_replace('@^https://api.github.com/repos/symfony/recipes(-contrib)?/contents/@', 'sf-recipes$1/', $url);
```
Comment (nicolas-grekas) [inline src/Downloader.php:418]: I'd suggest decoupling from symfony's repo, aka use this instead:
`$url = preg_replace('~^https://api.github.com/repos/([^/]++/[^/]++)/contents/', '$1/', $url);`

File: src/Downloader.php [hunk 2]
```diff
@@ -412,4 +412,11 @@ private function initialize()
...
+
+        return preg_replace('{[^a-z0-9.]}i', '-', $url);
```
Comment (jderusse) [inline src/Downloader.php:420]: to be sure that this bug won't occurs again, you could truncate the string (and adding hash to prevent collisions
```php
$maxLength = ???;
if (strlen($url) > $maxLength) {
  $url = substr($url, 0, $maxLength - 8).'-'.substr(sha1($url), 0, 7);
}

Comment (nicolas-grekas) [reply src/Downloader.php:420]: let's keep things simple for now at least :)

**Comment by nicolas-grekas** [comment]
Thank you @cjunge.
