### PR TITLE
Skip parallel downloader for local files

### LINKED ISSUE #560: Flex breaks composers artifact repository
Hi!

When using Flex I cannot install packages via composers built-in [artifact repository](https://getcomposer.org/doc/05-repositories.md#artifact).

**Expected behavior:**
Flex should not break composer built-in functionality.

**Actual behavior:**
My composer.json includes
```
    "repositories": [
        {
            "type": "artifact",
            "url": "var/installer/"
        }
    ]
```
and when having `symfony/flex:1.4.5` installed I run into this problem:
```
$ composer require foo/my-package 1.0
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Package operations: 1 install, 0 updates, 0 removal
  - Installing foo/my-package (1.0): Downloading (100%)
Downloading (100%)
Downloading (100%)

  [Composer\Downloader\TransportException]
  "var/installer/my-package-1.0.zip" appears broken, and returned an empty 200 response
```
When removing Symfony Flex the installation from my local zip works as expected.

**What I tried:**

Seeing `Downloading (100%)` 3 times lead me to `Composer\Downloader\FileDownloader` and its retries loop. So I debugged further (with and without Flex) and finally found the main difference being 
- `Composer\Util\RemoteFilesystem::getRemoteContents()` using `file_get_contents()` 
- `Symfony\Flex\ParallelDownloader::getRemoteContents()` using the `Symfony\Flex\CurlDownloader`

The latter fails when trying to use curl to fetch the zip from my local filesystem. 

@nicolas-grekas any idea how to work around that problem without removing flex? Is Flex supposed to work in such a setup?

I tried [replacing this line](https://github.com/symfony/flex/blob/master/src/ParallelDownloader.php#L247) with `if (stripos($originUrl, '://')  === false || !$this->downloader) {` and everything worked. But not knowing enough about composer internals I am not sure if this is the right place to start working on a bugfix.

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #560 

Currently Flex breaks installations of local packages via the composer built-in repository types:
- artifact repository (see #560)
- package repository (see #548)

This PR leaves the download to the original composer downloader, in case the URL of the package does not start with `http(s):`.

I found a very similar code piece in https://github.com/symfony/flex/blob/master/src/Flex.php#L605 (just for reference for maintainer).

### CODE REVIEW

File: src/ParallelDownloader.php [hunk 1]
```diff
@@ -244,7 +244,7 @@ protected function getRemoteContents($originUrl, $fileUrl, $context, array &$res
             return $result;
         }
 
-        if (!$this->downloader) {
+        if (!preg_match('/^https?:/', $originUrl) || !$this->downloader) {
```
Comment (stof) [inline src/ParallelDownloader.php]: I would swap the conditions. Checking for a `null` downloader is cheaper than running the regex.

Comment (kevinpapst) [reply src/ParallelDownloader.php]: True, changed.

**Comment by kevinpapst** [comment]
ping @nicolas-grekas @stof - anything else that I can/should do to progress?

**Comment by fabpot** [comment]
Thank you @kevinpapst.
