### PR TITLE
Fix problem of overwriting envs

### LINKED ISSUE #879: Flex changing bundles.php environments
We have a special bundles.php. Since some changes now flex seems to overwrite our `bundles.php` configurations which ends up in a none working version of @sulu as example we requires fixtures bundle be enabled in all environments and has other envs configured:

Bildschirmfoto 2022-03-03 um 14 10 54

I'm not sure which change in flex did this change. But it seems flex is ignoring exist entries in the `bundles.php` and there configuration and just overwrites them now. Which was not the case in the past.

### PR DESCRIPTION
**Pull request by alexander-schranz**
Fixes problem of flex overwriting bundles.php envs.

Fixes #879 which currently breaks @sulu skeleton installation.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Not sure how to fix:

>  Method getPackage may not return value of type Composer\Package\Package, its declared return type is "Composer\Package\RootPackageInterface"

File: tests/Configurator/DockerComposeConfiguratorTest.php [hunk 1]
```diff
@@ -114,7 +115,7 @@ class DockerComposeConfiguratorTest extends TestCase
     /** @var DockerComposeConfigurator */
     private $configurator;
 
-    /** @var Package */
```
Comment (alexander-schranz) [inline tests/Configurator/DockerComposeConfiguratorTest.php:117]: Trying here to fix: https://github.com/symfony/flex/runs/5509940830?check_suite_focus=true

File: tests/Configurator/DockerComposeConfiguratorTest.php [hunk 2]
```diff
@@ -114,7 +115,7 @@ class DockerComposeConfiguratorTest extends TestCase
...
+    /** @var PackageInterface */
```
Comment (alexander-schranz) [inline tests/Configurator/DockerComposeConfiguratorTest.php]: Trying here to fix: https://github.com/symfony/flex/runs/5509940830?check_suite_focus=true

But still errors this way: https://github.com/symfony/flex/runs/5510160271?check_suite_focus=true

File: src/Configurator/BundlesConfigurator.php [hunk 3]
```diff
@@ -69,12 +69,11 @@ private function configureBundles(array $bundles): array
             unset($classes[$fwb]);
         }
         foreach ($classes as $class => $envs) {
-            // if the class already existed, clear so we can update the envs
-            if (isset($registered[$class])) {
-                $registered[$class] = [];
-            }
-            foreach ($envs as $env) {
-                $registered[$class][$env] = true;
+            // do not override exist configured envs for a bundle
```
Comment (stof) [inline src/Configurator/BundlesConfigurator.php]: typo: `existing`

File: tests/Configurator/DockerComposeConfiguratorTest.php (hunk 2 above)
Comment (stof) [reply tests/Configurator/DockerComposeConfiguratorTest.php]: the error message you see here are coming from the mock configuration. So that's unrelated to that phpdoc

Comment (stof) [reply tests/Configurator/DockerComposeConfiguratorTest.php]: I think the right fix is to make it use a RootPackage instead of a Package for this property (but also for the actual value, not just for the comment)

Comment (alexander-schranz) [reply tests/Configurator/DockerComposeConfiguratorTest.php]: Thx that seems to fix the tests 👍 Had todo the same for LockArrayRepository in FlexTest.

Comment (alexander-schranz) [reply tests/Configurator/DockerComposeConfiguratorTest.php]: For backwards compatibility to composer 1.0.2 there a class_exists had to be added.

**Review by nicolas-grekas — APPROVED** [review]

**Review by fabpot — APPROVED** [review]

**Comment by fabpot** [comment]
Thank you @alexander-schranz.
