### PR TITLE
Fix BC break

### LINKED ISSUE #155: undefined method isNotInstallable on `composer update` while flex trying to update itself from 1.0.19 to 1.0.20
I was following the https://medium.com/@fabpot/symfony-4-a-quick-demo-da7d32be323
after the step `composer req cli` I added followings to the composer.json
        `"phpspec/phpspec": "^4.0"` to the `require-dev` section.
and 
        `"bin-dir": "bin",`  to the `config` section

current composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "symfony/console": "^3.3",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^3.3",
        "symfony/web-server-bundle": "^3.3",
        "symfony/yaml": "^3.3"
    },
    "require-dev": {
        "symfony/dotenv": "^3.3",
        "phpspec/phpspec": "^4.0"
    },
    "config": {
        "bin-dir": "bin",
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "auto-scripts": {
            "make cache-warmup": "script",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*",
        "symfony/twig-bundle": "<3.3",
        "symfony/debug": "<3.3"
    },
    "extra": {
        "symfony": {
            "id": "01BSY9G8E0C0W57C727W6XCDCB",
            "allow-contrib": false
        }
    }
}

```
then I hit 
```shell
 composer update
```
Result 
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 1 update, 0 removals
  - Updating symfony/flex (v1.0.19 => v1.0.20): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.0): Downloading (100%)
  - Installing doctrine/instantiator (1.1.0): Downloading (100%)
  - Installing sebastian/diff (2.0.1): Downloading (100%)
  - Installing sebastian/comparator (2.0.2): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (4.1.1): Downloading (100%)
  - Installing phpspec/prophecy (v1.7.2): Downloading (100%)
  - Installing phpspec/php-diff (v1.1.0): Downloading (100%)
  - Installing phpspec/phpspec (4.0.3): Downloading (100%)
Writing lock file
Generating autoload files
Symfony operations: 1 recipe
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Flex\Recipe::isNotInstallable() in /project/demo/vendor/symfony/flex/src/Flex.php:165
Stack trace:
#0 [internal function]: Symfony\Flex\Flex->update(Object(Composer\Script\Event))
#1 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#2 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Comp
oser\Script\Event))
#3 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#4 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/Command/UpdateCommand.php(158): Composer\Installer->run()
#5 /project/demo/vendor/symfony/flex/src/Co in /project/demo/vendor/symfony/flex/src/Flex.php on line 165

Fatal error: Uncaught Error: Call to undefined method Symfony\Flex\Recipe::isNotInstallable() in /project/demo/vendor/symfony/flex/src/Flex.php:165
Stack trace:
#0 [internal function]: Symfony\Flex\Flex->update(Object(Composer\Script\Event))
#1 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#2 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Comp
oser\Script\Event))
#3 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-update-cmd', true)
#4 phar:///usr/local/Cellar/composer/1.4.2/libexec/composer.phar/src/Composer/Command/UpdateCommand.php(158): Composer\Installer->run()
#5 /project/demo/vendor/symfony/flex/src/Co in /project/demo/vendor/symfony/flex/src/Flex.php on line 165
[1]    71388 exit 255   composer update
```

## UPDATE

I checked the diff https://github.com/symfony/flex/compare/v1.0.19...v1.0.20 but the problem is kind of strange. Basically Flex cannot update itself when there is a breaking change.  There should be a kind of process isolation could be an opcache or temporarily copy the source and load from it.

### PR DESCRIPTION
**Pull request by fabpot**
fixes #155

### CODE REVIEW

File: src/Recipe.php [hunk 1]
```diff
@@ -69,4 +69,16 @@ public function isContrib(): bool
     {
         return $this->data['is_contrib'] ?? false;
     }
+
+    // for BC, to be removed on 11/31/20177
```
Comment (hhamon) [inline src/Recipe.php]: `2017` maybe or that's a very long support ^^

File: src/Recipe.php [hunk 2]
```diff
@@ -69,4 +69,16 @@ public function isContrib(): bool
...
+    public function isNotInstallable(): bool
+    {
+        return $this->data['not_installable'] ?? false;
+    }
+
+    // for BC, to be removed on 11/31/20177
```
Comment (hhamon) [inline src/Recipe.php]: Same here.

File: src/Recipe.php (hunk 1 above)
Comment (hhamon) [reply src/Recipe.php]: Thus November has only 30 days ;)
