### PR TITLE
Fix dealing with locally patched packages

### LINKED ISSUE #508: Undefined index: version_normalized
Error: 
 * AppVeyor: https://ci.appveyor.com/project/fabpot/symfony/builds/25060723#L73
 * Travis: https://travis-ci.org/symfony/symfony/jobs/541735605#L2605

https://github.com/symfony/flex/blob/bc7390dcfa6d50e431e4d15b647544e59a6e3146/src/Cache.php#L82

or

https://github.com/symfony/flex/blob/bc7390dcfa6d50e431e4d15b647544e59a6e3146/src/Cache.php#L101

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fixes #508
Happens on the CI when local packages are built for testing PRs.

### CODE REVIEW

**Comment by fabpot** [comment]
Thank you @nicolas-grekas.

File: src/Cache.php [hunk 1]
```diff
@@ -78,6 +78,8 @@ public function removeLegacyTags(array $data): array
             foreach ($versions as $version => $composerJson) {
                 if ('dev-master' === $version) {
                     $normalizedVersion = $this->versionParser->normalize($devMasterAlias);
+                } elseif (!isset($composerJson['version_normalized'])) {
```
Comment (stof) [inline src/Cache.php]: why not attempting to read `$composerJson['version']`  and normalizing it (or just `$version`) ? We have access to the VersionParser to normalize here.

Comment (nicolas-grekas) [reply src/Cache.php]: because we don't really care: when this happens, we always want to keep the "version" anyway
