### PR TITLE
Fixing a small bug in detecting PHP files

### LINKED ISSUE #198: Uninstalling flex causes PHP Fatal Error
# How to reproduce:

1. Clone new Symfony skeleton project containing flex
2. Initialize project (including installing dev dependencies)
2. Run `composer install --no-dev`

Gives:

```
PHP Fatal error: Uncaught Error: Class 'Symfony\Flex\Response' not found in .../symfony/flex/src/Downloader.php:243
```

### PR DESCRIPTION
**Pull request by weaverryan**
Should fix #198 - the `substr` logic was just reversed a bit.

### CODE REVIEW

File: src/Flex.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function activate(Composer $composer, IOInterface $io)
         // to avoid issues when Flex is upgraded, we load all PHP classes now
         // that way, we are sure to use all files from the same version
         foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator(__DIR__, \FilesystemIterator::SKIP_DOTS)) as $file) {
-            if ('.php' === substr($file, 0, -4)) {
+            if ('.php' === substr($file, strlen($file) -4)) {
```
Comment (fabpot) [inline src/Flex.php]: `substr($file, -4)` is enough

**Comment by fabpot** [comment]
Thank you @weaverryan.
