### PR TITLE
Fix looking for keywords

### LINKED ISSUE #768: [Bug] v1.13.0: composer package-type "metapackage" conflicts with PackageJsonSynchronizer
Steps to reproduce:
* `composer global require "symfony/flex"`
* `echo '{}' > package.json`
* `composer require "gaufrette/ftp-adapter"`

Output:
```
  [ErrorException]
  file_get_contents(/home/starke/flex-test/vendor/gaufrette/ftp-adapter/composer.json): failed to open stream: No such file or directory
```

Composer version 2.0.13 2021-04-27 13:11:08
symfony/flex v1.13.0

This does not occur with v1.12.2

Assumed Explanation:
The [package-type](https://getcomposer.org/doc/04-schema.md#type) doesn't "write anything to the filesystem". Therefore the composer.json can not be read, as it isn't present.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fix #768

### CODE REVIEW

File: src/Flex.php [hunk 1]
```diff
@@ -593,9 +593,9 @@ private function synchronizePackageJson(string $rootDir)
         $synchronizer = new PackageJsonSynchronizer($rootDir, $vendorDir);
 
         if ($synchronizer->shouldSynchronize()) {
-            $packagesNames = array_column($this->composer->getLocker()->getLockData()['packages'] ?? [], 'name');
+            $lockData = $this->composer->getLocker()->getLockData();
 
-            if ($synchronizer->synchronize($packagesNames)) {
+            if ($synchronizer->synchronize($lockData['packages'] ?? []) || $synchronizer->synchronize($lockData['packages-dev'] ?? [])) {
```
Comment (nicolas-grekas) [inline src/Flex.php:598]: This was a bug, not looking at `packages-dev`, isn't it @tgalopin?

**Review by stof — APPROVED** [review]
